### PR TITLE
Use admin password which is easier to type out

### PR DESCRIPTION
**Pull request by justin-stephenson**
The IPA `admin` password is already simple, however it is not a quick one to type manually. This means I have to always keep the password in the copy-paste buffer, often times there are other commands which I need to copy and paste which interfere with this.

This PR sets a password than can be memorized and typed quicker, in my opinion.

### CODE REVIEW

**Comment by pbrezina** [comment]
It it super quick for me since I have a numpad but I don't oppose the change. But if we do change it, wouldn't it be better to use `vagrant` as password so it is consistent with AD?

**Comment by justin-stephenson** [comment]
`vagrant` works for me too, I'll update the PR in a bit.

Quick question, if this PR gets merged how would I go about tearing down my existing environment and re-deploying SSSD test suite to take advantage of the new changes?

**Comment by pbrezina** [comment]
```
$ git pull --rebase
$ ./sssd-test-suite destroy && ./sssd-test-suite provision enroll
```

**Comment by justin-stephenson** [comment]
Updated password to `vagrant` but maybe others prefer `123456789`, perhaps it would be good to get feedback from others using the test suite.

**Comment by pbrezina** [comment]
Sure, feel free to bring it up on the team list or on the meeting.

**Pull request closed without merging**
